#%RAML 1.0
protocols:
  - HTTPS
  - HTTP
mediaType: application/json
baseUri: ''
title: Get Salesforce Account Record
description: Get the Salesforce Account records
version: '1.0'
/Accounts:
  get:
    responses:
      '200':
        body:
          application/json:
            example:
              type: object
              properties:
                Name:
                  type: string
                Type:
                  type: string
                Lender_Identifier__c:
                  type: string
            type: object
